version: '3.5'

services:
  memcached:
    restart: always
    image: memcached:latest
    ports:
      - "11212:11211"
    container_name: memcached
    #networks:
    #  extnetwork:
    #    ipv4_address: 172.27.0.3
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - /var/www/html:/var/www/html
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
    environment:
      LANG: c.UTF-8
      TZ: Asia/Taipei
    #networks:
    #  extnetwork:
    #    ipv4_address: 172.27.0.4
  php742:
    restart: always
    build: ./php742
    expose:
      - "9000"
    container_name: php742
    volumes:
      - /home/tomcat/docker-compose-lnmp/php742/php.ini:/usr/local/etc/php/php.ini
      - /var/www/html:/var/www/html
    environment:
      LANG: c.UTF-8
      TZ: Asia/Taipei
    #networks:
    #  extnetwork:
    #    ipv4_address: 172.27.0.7
  mysql:
    restart: always
    build: ./mysql57
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - /home/tomcat/docker-compose-lnmp/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      LANG: c.UTF-8
      TZ: Asia/Taipei
    #networks:
    #  extnetwork:
    #    ipv4_address: 172.27.0.2

#networks:
#  extnetwork:
#    ipam:
#      config:
#        - subnet: 172.27.0.0/16
        #gateway: 172.27.0.1
